// app/terms/page.tsx
export default function TermsPage() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
      <p className="text-muted-foreground text-sm mb-8">Last updated: June 2026</p>

      <section className="space-y-6 text-sm text-foreground leading-relaxed">
        <div>
          <h2 className="font-semibold text-base mb-2">Using InterviewAI</h2>
          <p>By using this service you agree to use it for lawful purposes only. You must be 13 or older to create an account.</p>
        </div>
        <div>
          <h2 className="font-semibold text-base mb-2">Interview Pack</h2>
          <p>The Interview Pack is a one-time payment of $17. It grants 5 mock interview sessions and access to the full Countdown Kit for 30 days from the date of purchase. No refunds after sessions have been used.</p>
        </div>
        <div>
          <h2 className="font-semibold text-base mb-2">AI-generated content</h2>
          <p>Questions, feedback, and documents are generated by AI and are provided for practice purposes only. They do not guarantee interview success and should not be treated as professional career advice.</p>
        </div>
        <div>
          <h2 className="font-semibold text-base mb-2">Account termination</h2>
          <p>We reserve the right to suspend or terminate accounts that abuse the service or violate these terms.</p>
        </div>
        <div>
          <h2 className="font-semibold text-base mb-2">Limitation of liability</h2>
          <p>InterviewAI is provided "as is" without warranty. We are not liable for any damages arising from use of the service.</p>
        </div>
        <div>
          <h2 className="font-semibold text-base mb-2">Contact</h2>
          <p>Questions? Email janamrangani@gmail.com</p>
        </div>
      </section>
    </main>
  );
}
